CC = gcc
PARAMS = -std=gnu99 -Wall -Werror -Wextra -pedantic -g
THREAD = -lrt -pthread

all:
	${CC} ${PARAMS} -o proj2 proj2.c ${THREAD}

proj2:
	${CC} ${PARAMS} -o proj2 proj2.c ${THREAD}
	
clean:
	rm -frv proj2
